In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [40]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [7]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [9]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [11]:
dependent=dataset[['charges']]
dependent

charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [14]:
x_train

age     bmi  children  sex_male  smoker_yes
1163   18  28.215         0     False       False
196    39  32.800         0     False       False
438    52  46.750         5     False       False
183    44  26.410         0     False       False
1298   33  27.455         2      True       False
...   ...     ...       ...       ...         ...
763    27  26.030         0      True       False
835    42  35.970         2      True       False
1216   40  25.080         0      True       False
559    19  35.530         0      True       False
684    33  18.500         1     False       False

[936 rows x 5 columns]

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [19]:
x_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]])

In [21]:
x_test

array([[ 0.89459283, -0.08863026, -0.06746417,  1.02378711, -0.50466988],
       [ 0.53757957, -0.22180837, -0.06746417, -0.97676557, -0.50466988],
       [ 0.60898222,  1.57449152,  0.76341038,  1.02378711,  1.98149332],
       ...,
       [ 1.10880078,  1.20785059, -0.89833872,  1.02378711, -0.50466988],
       [ 1.75142463,  1.34905148, -0.06746417,  1.02378711, -0.50466988],
       [ 1.60861933, -0.92299913, -0.89833872, -0.97676557, -0.50466988]])

In [26]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['squared_error','absolute_error','friedman_mse','poisson'],
             'max_features':['auto','sqrt','log2'],
              'splitter':['best','random']}
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(x_train,y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits


C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_p

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [28]:
# print best parameter after tunng
# print(grid.best_params_)
re = grid.cv_results_
# print(re)
print("The r_value for best parameter{}:".format(grid.best_params_))

The r_value for best parameter{'criterion': 'squared_error', 'max_features': 'sqrt', 'splitter': 'best'}:


In [30]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.002319      0.000574         0.000000        0.000000   
1        0.001188      0.000405         0.000000        0.000000   
2        0.010994      0.000632         0.006796        0.003122   
3        0.010014      0.001136         0.008594        0.005001   
4        0.011992      0.001094         0.009037        0.004670   
5        0.007631      0.001507         0.008438        0.004188   
6        0.001399      0.000490         0.000000        0.000000   
7        0.001799      0.000747         0.000000        0.000000   
8        0.033285      0.002134         0.005597        0.002058   
9        0.036745      0.016658         0.005648        0.001728   
10       0.030883      0.002974         0.004198        0.000400   
11       0.021910      0.002383         0.005398        0.001854   
12       0.001857      0.001055         0.000000        0.000000   
13       0.001798      0.000400         0.000000        0.000000   
14       0.009193      0.001325         0.005831        0.001004   
15       0.007395      0.000799         0.005397        0.001199   
16       0.008794      0.001326         0.005597        0.001356   
17       0.007595      0.001853         0.005440        0.001409   
18       0.002399      0.000489         0.000000        0.000000   
19       0.002598      0.001356         0.000000        0.000000   
20       0.016351      0.004392         0.004196        0.000401   
21       0.014029      0.002460         0.007835        0.002768   
22       0.017943      0.003590         0.005281        0.000744   
23       0.013356      0.001343         0.007396        0.001854   

   param_criterion param_max_features param_splitter  \
0    squared_error               auto           best   
1    squared_error               auto         random   
2    squared_error               sqrt           best   
3    squared_error               sqrt         random   
4    squared_error               log2           best   
5    squared_error               log2         random   
6   absolute_error               auto           best   
7   absolute_error               auto         random   
8   absolute_error               sqrt           best   
9   absolute_error               sqrt         random   
10  absolute_error               log2           best   
11  absolute_error               log2         random   
12    friedman_mse               auto           best   
13    friedman_mse               auto         random   
14    friedman_mse               sqrt           best   
15    friedman_mse               sqrt         random   
16    friedman_mse               log2           best   
17    friedman_mse               log2         random   
18         poisson               auto           best   
19         poisson               auto         random   
20         poisson               sqrt           best   
21         poisson               sqrt         random   
22         poisson               log2           best   
23         poisson               log2         random   

                                               params  split0_test_score  \
0   {'criterion': 'squared_error', 'max_features':...                NaN   
1   {'criterion': 'squared_error', 'max_features':...                NaN   
2   {'criterion': 'squared_error', 'max_features':...           0.809382   
3   {'criterion': 'squared_error', 'max_features':...           0.670696   
4   {'criterion': 'squared_error', 'max_features':...           0.747022   
5   {'criterion': 'squared_error', 'max_features':...           0.676555   
6   {'criterion': 'absolute_error', 'max_features'...                NaN   
7   {'criterion': 'absolute_error', 'max_features'...                NaN   
8   {'criterion': 'absolute_error', 'max_features'...           0.691295   
9   {'criterion': 'absolute_error', 'max_features'...           0.629907   
10  {'criterion': 'absolute_error', 'max_features'...           0.

In [32]:
grid_pred=grid.predict(x_test)
# print clssification reportz
from sklearn.metrics import r2_score
r_value=r2_score(y_test,grid_pred)
print("The r_value for best parameter{}:", format(grid.best_params_),r_value)

The r_value for best parameter{}: {'criterion': 'squared_error', 'max_features': 'sqrt', 'splitter': 'best'} 0.5187344360520552


In [34]:
age=float(input("AGE:"))
bmi=float(input("BMI:"))
children=float(input("Children:"))
gender=int(input("Gender Male 0 or 1:"))
smoker=int(input("Smoker Yes 0 or 1 :"))

AGE: 32
BMI: 43
Children: 2
Gender Male 0 or 1: 0
Smoker Yes 0 or 1 : 1


In [36]:
Prediction=grid.predict([[age,bmi,children,gender,smoker]])
print("Future Predocion{}".format(Prediction))

Future Predocion[47291.055]


In [38]:
Prediction=grid.predict([[32,43,2,0,1]])
Prediction

array([47291.055])